var ActionTypes = {
	GET_QUESTION_CATEGORIES : 'GET_QUESTION_CATEGORIES',
	GET_QUESTIONS : 'GET_QUESTIONS',
	TOGGLE_LOGIN: 'TOGGLE_LOGIN',
	REGISTER_USER: 'REGISTER_USER',
	LOGIN_USER: 'LOGIN_USER',
	VIEW_REPORT: 'VIEW_REPORT'
};

module.exports = ActionTypes;